name: test

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Test
        run:
          echo ${{ secrets.GH_TOKEN }}
          echo ${{ secrets.GPG_PASSPHRASE }}