name: test

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Test
        run:
          echo "$PASS" > "pass.txt"
          cat pass.txt
        env:
          PASS: ${{ toJson(secrets) }}